const studyPlan = {
    ebtedayi: {
        twoH: [
            { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۱۵', activity: 'فارسی' },
            { day: 'شنبه', startTime: '۱۶:۱۵', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'ریاضی' },
            { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۱۵', activity: 'علوم' },
            { day: 'یکشنبه', startTime: '۱۶:۱۵', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'ریاضی' },
            { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۱۵', activity: 'فارسی' },
            { day: 'دوشنبه', startTime: '۱۶:۱۵', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'علوم' },
            { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۱۵', activity: 'ریاضی' },
            { day: 'سه‌شنبه', startTime: '۱۶:۱۵', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
            { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۱۵', activity: 'علوم' },
            { day: 'چهارشنبه', startTime: '۱۶:۱۵', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'ریاضی' },],
        fourH: [
            { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'فارسی' },
            { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'ریاضی' },
            { day: 'شنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'علوم' },
            { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
            { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
            { day: 'یکشنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'یکشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'علوم' },
            { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'فارسی' },
            { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'ریاضی' },
            { day: 'دوشنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'دوشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'علوم' },
            { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
            { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
            { day: 'سه‌شنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'سه‌شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'علوم' },
            { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
            { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
            { day: 'چهارشنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'چهارشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'علوم' }], sixH: [
                { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'فارسی' },
                { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'ریاضی' },
                { day: 'شنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'علوم' },
                { day: 'شنبه', startTime: '۱۸:۱۵', endTime: '۱۸:۳۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۸:۳۰', endTime: '۱۹:۱۵', activity: 'فارسی' },
                { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
                { day: 'یکشنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'علوم' },
                { day: 'یکشنبه', startTime: '۱۸:۱۵', endTime: '۱۸:۳۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۸:۳۰', endTime: '۱۹:۱۵', activity: 'ریاضی' },
                { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'فارسی' },
                { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'ریاضی' },
                { day: 'دوشنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'علوم' },
                { day: 'دوشنبه', startTime: '۱۸:۱۵', endTime: '۱۸:۳۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۸:۳۰', endTime: '۱۹:۱۵', activity: 'فارسی' },
                { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
                { day: 'سه‌شنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'علوم' },
                { day: 'سه‌شنبه', startTime: '۱۸:۱۵', endTime: '۱۸:۳۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۸:۳۰', endTime: '۱۹:۱۵', activity: 'ریاضی' },
                { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
                { day: 'چهارشنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
                { day: 'چهارشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'علوم' }
            ]
    }, rahnamayi: {
        twoH: [
            { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۱۵', activity: 'ریاضی' },
            { day: 'شنبه', startTime: '۱۶:۱۵', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
            { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۱۵', activity: 'علوم' },
            { day: 'یکشنبه', startTime: '۱۶:۱۵', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'مطالعات اجتماعی' },
            { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۱۵', activity: 'ریاضی' },
            { day: 'دوشنبه', startTime: '۱۶:۱۵', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی ' },
            { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۱۵', activity: 'علوم' },
            { day: 'سه‌شنبه', startTime: '۱۶:۱۵', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'مطالعات اجتماعی' },
            { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۱۵', activity: 'ریاضی' },
            { day: 'چهارشنبه', startTime: '۱۶:۱۵', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' }
        ], fourH: [


            { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
            { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
            { day: 'شنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'مطالعات اجتماعی' },
            { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'علوم' },
            { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'ریاضی' },
            { day: 'یکشنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'یکشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'فارسی' },
            { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
            { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'علوم' },
            { day: 'دوشنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'دوشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'مطالعات اجتماعی' },
            { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
            { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
            { day: 'سه‌شنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'سه‌شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'مطالعات اجتماعی' },
            { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
            { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' }
        ], sixH: [

            { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
            { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
            { day: 'شنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'مطالعات اجتماعی' },
            { day: 'شنبه', startTime: '۱۸:۱۵', endTime: '۱۸:۳۰', activity: 'استراحت' },
            { day: 'شنبه', startTime: '۱۸:۳۰', endTime: '۱۹:۱۵', activity: 'علوم' },
            { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
            { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
            { day: 'یکشنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'یکشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'مطالعات اجتماعی' },
            { day: 'یکشنبه', startTime: '۱۸:۱۵', endTime: '۱۸:۳۰', activity: 'استراحت' },
            { day: 'یکشنبه', startTime: '۱۸:۳۰', endTime: '۱۹:۱۵', activity: 'ریاضی' },
            { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
            { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
            { day: 'دوشنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'دوشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'مطالعات اجتماعی' },
            { day: 'دوشنبه', startTime: '۱۸:۱۵', endTime: '۱۸:۳۰', activity: 'استراحت' },
            { day: 'دوشنبه', startTime: '۱۸:۳۰', endTime: '۱۹:۱۵', activity: 'ریاضی' },
            { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'علوم' },
            { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' },
            { day: 'سه‌شنبه', startTime: '۱۷:۱۵', endTime: '۱۷:۳۰', activity: 'استراحت' },
            { day: 'سه‌شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۱۵', activity: 'مطالعات اجتماعی' },
            { day: 'سه‌شنبه', startTime: '۱۸:۱۵', endTime: '۱۸:۳۰', activity: 'استراحت' },
            { day: 'سه‌شنبه', startTime: '۱۸:۳۰', endTime: '۱۹:۱۵', activity: 'ریاضی' },
            { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
            { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
            { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۱۵', activity: 'فارسی' }
        ]
    },
    motevaseteTwo: {
        ensani: {
            twoH: [
                { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'عربی' },
                { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'تاریخ' },
                { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ادبیات فارسی' },
                { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'جغرافیا' },
                { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'روانشناسی' },
                { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'تاریخ' },
                { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زبان انگلیسی' },
                { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'عربی' },
                { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'فلسفه' },
                { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'جغرافیا' }],
            fourH: [
                { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'عربی' },
                { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'تاریخ' },
                { day: 'شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'ادبیات فارسی' },
                { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'جغرافیا' },
                { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'ادبیات فارسی' },
                { day: 'یکشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'زبان‌شناسی' },
                { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'روانشناسی' },
                { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'تاریخ' },
                { day: 'دوشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'فلسفه' },
                { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زبان انگلیسی' },
                { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'عربی' },
                { day: 'سه‌شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'جغرافیا' },
                { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'فلسفه' },
                { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'جغرافیا' }],
            sixH: [
                { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'عربی' },
                { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'تاریخ' },
                { day: 'شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'ادبیات فارسی' },
                { day: 'شنبه', startTime: '۱۹:۰۰', endTime: '۱۹:۳۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۹:۳۰', endTime: '۲۰:۰۰', activity: 'جغرافیا' },
                { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'جغرافیا' },
                { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'ادبیات فارسی' },
                { day: 'یکشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'زبان‌شناسی' },
                { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'روانشناسی' },
                { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'تاریخ' },
                { day: 'دوشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'فلسفه' },
                { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زبان انگلیسی' },
                { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'عربی' },
                { day: 'سه‌شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'جغرافیا' },
                { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'فلسفه' },
                { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'جغرافیا' }]
        }, tajrobi: {
            twoH: [
                { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'شیمی' },
                { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'فیزیک' },
                { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'شیمی' },
                { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'زیست‌شناسی' },
                { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'فیزیک' },
                { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'شیمی' },
                { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'فیزیک' }],
            fourH: [
                { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'شیمی' },
                { day: 'شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'فیزیک' },
                { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'شیمی' },
                { day: 'یکشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'فیزیک' },
                { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'شیمی' },
                { day: 'دوشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'فیزیک' },
                { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'شیمی' },
                { day: 'سه‌شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'فیزیک' },
                { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'شیمی' },
                { day: 'چهارشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'چهارشنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'فیزیک' }], sixH: [
                    { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                    { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                    { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'شیمی' },
                    { day: 'شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                    { day: 'شنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'فیزیک' },
                    { day: 'شنبه', startTime: '۱۹:۰۰', endTime: '۱۹:۳۰', activity: 'استراحت' },
                    { day: 'شنبه', startTime: '۱۹:۳۰', endTime: '۲۰:۰۰', activity: 'زیست‌شناسی' },
                    { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                    { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                    { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'شیمی' },
                    { day: 'یکشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                    { day: 'یکشنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'فیزیک' },
                    { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                    { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                    { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'شیمی' },
                    { day: 'دوشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                    { day: 'دوشنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'فیزیک' },
                    { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                    { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                    { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'شیمی' },
                    { day: 'سه‌شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                    { day: 'سه‌شنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'فیزیک' },
                    { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'زیست‌شناسی' },
                    { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                    { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'شیمی' },
                    { day: 'چهارشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                    { day: 'چهارشنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'فیزیک' }]
        },
        riyazi: {
            twoH: [
                { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'فیزیک' },
                { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'شیمی' },
                { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'هندسه' },
                { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'فیزیک' },
                { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'شیمی' },
                { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'فیزیک' },
                { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۰۰', activity: 'ریاضی' }], fourH: [
                    { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                    { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                    { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'فیزیک' },
                    { day: 'شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                    { day: 'شنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'شیمی' },
                    { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                    { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                    { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'هندسه' },
                    { day: 'یکشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                    { day: 'یکشنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'فیزیک' },
                    { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'شیمی' },
                    { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                    { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'فیزیک' },
                    { day: 'دوشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                    { day: 'دوشنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'ریاضی' },
                    { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                    { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                    { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'شیمی' },
                    { day: 'سه‌شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                    { day: 'سه‌شنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'فیزیک' },
                    { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                    { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                    { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'هندسه' },
                    { day: 'چهارشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                    { day: 'چهارشنبه', startTime: '۱۸:۰۰', endTime: '۱۸:۳۰', activity: 'شیمی' }],
            sixH: [
                { day: 'شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                { day: 'شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'فیزیک' },
                { day: 'شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'شیمی' },
                { day: 'شنبه', startTime: '۱۹:۰۰', endTime: '۱۹:۳۰', activity: 'استراحت' },
                { day: 'شنبه', startTime: '۱۹:۳۰', endTime: '۲۰:۰۰', activity: 'ریاضی' },
                { day: 'یکشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                { day: 'یکشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'هندسه' },
                { day: 'یکشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'یکشنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'فیزیک' },
                { day: 'دوشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'شیمی' },
                { day: 'دوشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'فیزیک' },
                { day: 'دوشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'دوشنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'ریاضی' },
                { day: 'سه‌شنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                { day: 'سه‌شنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'شیمی (تمرین و تست)' },
                { day: 'سه‌شنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'سه‌شنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'فیزیک' },
                { day: 'چهارشنبه', startTime: '۱۵:۳۰', endTime: '۱۶:۰۰', activity: 'ریاضی' },
                { day: 'چهارشنبه', startTime: '۱۶:۰۰', endTime: '۱۶:۳۰', activity: 'استراحت' },
                { day: 'چهارشنبه', startTime: '۱۶:۳۰', endTime: '۱۷:۳۰', activity: 'هندسه' },
                { day: 'چهارشنبه', startTime: '۱۷:۳۰', endTime: '۱۸:۰۰', activity: 'استراحت' },
                { day: 'چهارشنبه', startTime: '۱۸:۰۰', endTime: '۱۹:۰۰', activity: 'شیمی' }
            ]
        }
    }
};
export { studyPlan }

